workspace:
  root: ./
variables:
- dims:
  - time
  - x
  ids: core_profiles
  name: rho_tor_norm
  path: profiles_1d/*/grid/rho_tor_norm
- dims:
  - time
  - x
  ids: core_profiles
  name: t_i_average
  path: profiles_1d/*/t_i_average
- dims:
  - time
  - x
  ids: core_profiles
  name: zeff
  path: profiles_1d/*/zeff
- dims:
  - time
  ids: core_profiles
  name: time
  path: time
create:
  template: template_model
  data:
    imasdb: test
    run_in_start_at: 7000
    run_out_start_at: 8000
  sampler:
    method: latin-hypercube
    n_samples: 1
  dimensions:
    - variable: zeff
      operator: add
      values: [1, 2, 3]
    - variable: t_i_average
      operator: multiply
      values: [1.1, 1.2, 1.3]
system: jetto-duqtools
status:
  msg_completed: 'Status : Completed successfully'
  msg_failed: 'Status : Failed'
  msg_running: 'Status : Running'
  status_file: jetto.status
submit:
  submit_script_name: .llcmd
