name: Build IMAS and run tests

on:
  pull_request:
    branches:
      - main
    # types:
    #   - opened
    #   - reopened
    #   - synchronize
    #   - ready_for_review
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test2:
    # if: github.event.pull_request.draft == false
    name: ${{ matrix.os }}, ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.9']

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache-imas
        with:
          path: imas
          key: imas-install-123

      - name: Install libraries
        if: steps.cache-imas.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y xsltproc

      - name: Download data-dictionary
        if: steps.cache-imas.outputs.cache-hit != 'true'
        run: |
          username="smeetss"
          password="${{ secrets.GIT_ITER_ORG_HTTPS_KEY }}"
          git clone https://$username:$password@git.iter.org/scm/imas/data-dictionary.git imas/data-dictionary

      - name: Download access-layer
        if: steps.cache-imas.outputs.cache-hit != 'true'
        run: |
          username="smeetss"
          password="${{ secrets.GIT_ITER_ORG_HTTPS_KEY }}"
          git clone --depth=1 https://$username:$password@git.iter.org/scm/imas/access-layer.git imas/access-layer

      - name: Download saxon9he.jar
        if: steps.cache-imas.outputs.cache-hit != 'true'
        run: |
          mkdir saxon9he
          cd saxon9he
          curl -L https://sourceforge.net/projects/saxon/files/Saxon-HE/9.9/SaxonHE9-9-1-7J.zip/download -o saxon9he.zip
          unzip saxon9he.zip

      - name: Download blitz
        if: steps.cache-imas.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/blitzpp/blitz
          cd blitz
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=../local/ ..
          make lib
          make install
          cd ../..

      - name: Build imas
        if: steps.cache-imas.outputs.cache-hit != 'true'
        run: |
          cd imas
          mv ../saxon9he/saxon9he.jar .
          ln -s ../testing/build_imas_script.sh .
          . build_imas_script.sh
          cd ..

      - name: Test imas import
        run: |
          . ./imas/source_me.sh
          python -c 'import imas'
